/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AigcRouteImport } from './routes/aigc'
import { Route as IndexRouteImport } from './routes/index'

const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AigcRoute = AigcRouteImport.update({
  id: '/aigc',
  path: '/aigc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aigc': typeof AigcRoute
  '/assets': typeof AssetsRoute
  '/publish': typeof PublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aigc': typeof AigcRoute
  '/assets': typeof AssetsRoute
  '/publish': typeof PublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aigc': typeof AigcRoute
  '/assets': typeof AssetsRoute
  '/publish': typeof PublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aigc' | '/assets' | '/publish'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aigc' | '/assets' | '/publish'
  id: '__root__' | '/' | '/aigc' | '/assets' | '/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AigcRoute: typeof AigcRoute
  AssetsRoute: typeof AssetsRoute
  PublishRoute: typeof PublishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aigc': {
      id: '/aigc'
      path: '/aigc'
      fullPath: '/aigc'
      preLoaderRoute: typeof AigcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AigcRoute: AigcRoute,
  AssetsRoute: AssetsRoute,
  PublishRoute: PublishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
