/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPublishRouteImport } from './routes/_authenticated/publish'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedAigcIndexRouteImport } from './routes/_authenticated/aigc.index'
import { Route as AuthenticatedAigcVideoRouteImport } from './routes/_authenticated/aigc.video'
import { Route as AuthenticatedAigcOneclickRouteImport } from './routes/_authenticated/aigc.oneclick'
import { Route as AuthenticatedAigcImageRouteImport } from './routes/_authenticated/aigc.image'
import { Route as AuthenticatedAigcCopyRouteImport } from './routes/_authenticated/aigc.copy'
import { Route as ApiPublicWorkerCronTickRouteImport } from './routes/api/public/worker/cron-tick'
import { Route as ApiPublicWorkerCallbackRouteImport } from './routes/api/public/worker/callback'
import { Route as ApiPublicCronAutomationTickRouteImport } from './routes/api/public/cron/automation-tick'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishRoute = AuthenticatedPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAigcIndexRoute = AuthenticatedAigcIndexRouteImport.update({
  id: '/aigc/',
  path: '/aigc/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAigcVideoRoute = AuthenticatedAigcVideoRouteImport.update({
  id: '/aigc/video',
  path: '/aigc/video',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAigcOneclickRoute =
  AuthenticatedAigcOneclickRouteImport.update({
    id: '/aigc/oneclick',
    path: '/aigc/oneclick',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAigcImageRoute = AuthenticatedAigcImageRouteImport.update({
  id: '/aigc/image',
  path: '/aigc/image',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAigcCopyRoute = AuthenticatedAigcCopyRouteImport.update({
  id: '/aigc/copy',
  path: '/aigc/copy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWorkerCronTickRoute = ApiPublicWorkerCronTickRouteImport.update({
  id: '/api/public/worker/cron-tick',
  path: '/api/public/worker/cron-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerCallbackRoute = ApiPublicWorkerCallbackRouteImport.update({
  id: '/api/public/worker/callback',
  path: '/api/public/worker/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAutomationTickRoute =
  ApiPublicCronAutomationTickRouteImport.update({
    id: '/api/public/cron/automation-tick',
    path: '/api/public/cron/automation-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/aigc/copy': typeof AuthenticatedAigcCopyRoute
  '/aigc/image': typeof AuthenticatedAigcImageRoute
  '/aigc/oneclick': typeof AuthenticatedAigcOneclickRoute
  '/aigc/video': typeof AuthenticatedAigcVideoRoute
  '/aigc/': typeof AuthenticatedAigcIndexRoute
  '/api/public/cron/automation-tick': typeof ApiPublicCronAutomationTickRoute
  '/api/public/worker/callback': typeof ApiPublicWorkerCallbackRoute
  '/api/public/worker/cron-tick': typeof ApiPublicWorkerCronTickRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/aigc/copy': typeof AuthenticatedAigcCopyRoute
  '/aigc/image': typeof AuthenticatedAigcImageRoute
  '/aigc/oneclick': typeof AuthenticatedAigcOneclickRoute
  '/aigc/video': typeof AuthenticatedAigcVideoRoute
  '/aigc': typeof AuthenticatedAigcIndexRoute
  '/api/public/cron/automation-tick': typeof ApiPublicCronAutomationTickRoute
  '/api/public/worker/callback': typeof ApiPublicWorkerCallbackRoute
  '/api/public/worker/cron-tick': typeof ApiPublicWorkerCronTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/publish': typeof AuthenticatedPublishRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/aigc/copy': typeof AuthenticatedAigcCopyRoute
  '/_authenticated/aigc/image': typeof AuthenticatedAigcImageRoute
  '/_authenticated/aigc/oneclick': typeof AuthenticatedAigcOneclickRoute
  '/_authenticated/aigc/video': typeof AuthenticatedAigcVideoRoute
  '/_authenticated/aigc/': typeof AuthenticatedAigcIndexRoute
  '/api/public/cron/automation-tick': typeof ApiPublicCronAutomationTickRoute
  '/api/public/worker/callback': typeof ApiPublicWorkerCallbackRoute
  '/api/public/worker/cron-tick': typeof ApiPublicWorkerCronTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/assets'
    | '/publish'
    | '/settings'
    | '/aigc/copy'
    | '/aigc/image'
    | '/aigc/oneclick'
    | '/aigc/video'
    | '/aigc/'
    | '/api/public/cron/automation-tick'
    | '/api/public/worker/callback'
    | '/api/public/worker/cron-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/accounts'
    | '/assets'
    | '/publish'
    | '/settings'
    | '/'
    | '/aigc/copy'
    | '/aigc/image'
    | '/aigc/oneclick'
    | '/aigc/video'
    | '/aigc'
    | '/api/public/cron/automation-tick'
    | '/api/public/worker/callback'
    | '/api/public/worker/cron-tick'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/assets'
    | '/_authenticated/publish'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/aigc/copy'
    | '/_authenticated/aigc/image'
    | '/_authenticated/aigc/oneclick'
    | '/_authenticated/aigc/video'
    | '/_authenticated/aigc/'
    | '/api/public/cron/automation-tick'
    | '/api/public/worker/callback'
    | '/api/public/worker/cron-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronAutomationTickRoute: typeof ApiPublicCronAutomationTickRoute
  ApiPublicWorkerCallbackRoute: typeof ApiPublicWorkerCallbackRoute
  ApiPublicWorkerCronTickRoute: typeof ApiPublicWorkerCronTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publish': {
      id: '/_authenticated/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof AuthenticatedPublishRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aigc/': {
      id: '/_authenticated/aigc/'
      path: '/aigc'
      fullPath: '/aigc/'
      preLoaderRoute: typeof AuthenticatedAigcIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aigc/video': {
      id: '/_authenticated/aigc/video'
      path: '/aigc/video'
      fullPath: '/aigc/video'
      preLoaderRoute: typeof AuthenticatedAigcVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aigc/oneclick': {
      id: '/_authenticated/aigc/oneclick'
      path: '/aigc/oneclick'
      fullPath: '/aigc/oneclick'
      preLoaderRoute: typeof AuthenticatedAigcOneclickRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aigc/image': {
      id: '/_authenticated/aigc/image'
      path: '/aigc/image'
      fullPath: '/aigc/image'
      preLoaderRoute: typeof AuthenticatedAigcImageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aigc/copy': {
      id: '/_authenticated/aigc/copy'
      path: '/aigc/copy'
      fullPath: '/aigc/copy'
      preLoaderRoute: typeof AuthenticatedAigcCopyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/worker/cron-tick': {
      id: '/api/public/worker/cron-tick'
      path: '/api/public/worker/cron-tick'
      fullPath: '/api/public/worker/cron-tick'
      preLoaderRoute: typeof ApiPublicWorkerCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/callback': {
      id: '/api/public/worker/callback'
      path: '/api/public/worker/callback'
      fullPath: '/api/public/worker/callback'
      preLoaderRoute: typeof ApiPublicWorkerCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/automation-tick': {
      id: '/api/public/cron/automation-tick'
      path: '/api/public/cron/automation-tick'
      fullPath: '/api/public/cron/automation-tick'
      preLoaderRoute: typeof ApiPublicCronAutomationTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedPublishRoute: typeof AuthenticatedPublishRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAigcCopyRoute: typeof AuthenticatedAigcCopyRoute
  AuthenticatedAigcImageRoute: typeof AuthenticatedAigcImageRoute
  AuthenticatedAigcOneclickRoute: typeof AuthenticatedAigcOneclickRoute
  AuthenticatedAigcVideoRoute: typeof AuthenticatedAigcVideoRoute
  AuthenticatedAigcIndexRoute: typeof AuthenticatedAigcIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedPublishRoute: AuthenticatedPublishRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAigcCopyRoute: AuthenticatedAigcCopyRoute,
  AuthenticatedAigcImageRoute: AuthenticatedAigcImageRoute,
  AuthenticatedAigcOneclickRoute: AuthenticatedAigcOneclickRoute,
  AuthenticatedAigcVideoRoute: AuthenticatedAigcVideoRoute,
  AuthenticatedAigcIndexRoute: AuthenticatedAigcIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronAutomationTickRoute: ApiPublicCronAutomationTickRoute,
  ApiPublicWorkerCallbackRoute: ApiPublicWorkerCallbackRoute,
  ApiPublicWorkerCronTickRoute: ApiPublicWorkerCronTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
